### ISSUE TITLE
Empty description file causes loader to raise exception and exit

### ISSUE THREAD

**Issue by coleslaw481** [ndexcontent/ndexsignorloader#1]
The description for `SIGNOR-AML-IDH-TET` from signor is empty causing the loader to exit with the following exception:

```
Traceback (most recent call last):
  File "/Users/churas/anaconda3/envs/networkx2/bin/ndexloadsignor.py", line 1952, in main
    return loader.run()
  File "/Users/churas/anaconda3/envs/networkx2/bin/ndexloadsignor.py", line 1865, in run
    report_list.append(self._process_pathway(key, pathway_map[key]))
  File "/Users/churas/anaconda3/envs/networkx2/bin/ndexloadsignor.py", line 1623, in _process_pathway
    pathway_name=pathway_name)
  File "/Users/churas/anaconda3/envs/networkx2/bin/ndexloadsignor.py", line 1760, in _add_pathway_info
    dataframe = self._get_signor_pathway_description_df(pathway_id)
  File "/Users/churas/anaconda3/envs/networkx2/bin/ndexloadsignor.py", line 1582, in _get_signor_pathway_description_df
    engine='python')
  File "/Users/churas/anaconda3/envs/networkx2/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/churas/anaconda3/envs/networkx2/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/churas/anaconda3/envs/networkx2/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/Users/churas/anaconda3/envs/networkx2/lib/python3.7/site-packages/pandas/io/parsers.py", line 1132, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/Users/churas/anaconda3/envs/networkx2/lib/python3.7/site-packages/pandas/io/parsers.py", line 2238, in __init__
    self.unnamed_cols) = self._infer_columns()
  File "/Users/churas/anaconda3/envs/networkx2/lib/python3.7/site-packages/pandas/io/parsers.py", line 2532, in _infer_columns
    "No columns to parse from file")
pandas.errors.EmptyDataError: No columns to parse from file
```

In case of empty description, the loader should just use the name from the pathway list if possible and coming soon for description and curators. A warning message should also be output to the user invoking the script.

**Comment by coleslaw481** [comment]
The easiest fix is to just catch the exception in `_get_signor_pathway_description_df()` and return a manually created data frame, but the user won't get notified of the issue unless we update this function and `_add_pathway_info` to return any issues encountered.

**Comment by coleslaw481** [comment]
Fixed in commit https://github.com/ndexcontent/ndexsignorloader/commit/5951a632d80469d9b75f0ced93074af2c6836fff
